{"codes":[
  {"name":"636 - SYBERRY - Скидка 10% - От 16.99 рублей - Минск","code":"SYBERRY","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"640 - POTATO - Картофельные дольки - От 15.00 рублей - Минск","code":"POTATO","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"718 - QULIX1 - Скидка 10% - От 70.00 рублей - Минск","code":"QULIX1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"794 - ПЛЭЙТИКА - Скидка 10% - От 16.99 рублей - Минск","code":"ПЛЭЙТИКА","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"795 - ПЛЭЙТИКА1 - Скидка 10% - От 70.00 рублей - Минск","code":"ПЛЭЙТИКА1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"840 - ХАЙНЕКЕН - Скидка 10% - От 16.99 рублей - Минск","code":"ХАЙНЕКЕН","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"841 - ХАЙНЕКЕН1 - Скидка 10% - От 70.00 рублей - Минск","code":"ХАЙНЕКЕН1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"901 - МТС - Скидка 10% - От 16.99 рублей - Минск","code":"МТС","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"902 - МТС10 - Скидка 10% - От 70.00 рублей - Минск","code":"МТС10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"903 - A1QA - Скидка 10% - От 16.99 рублей - Минск","code":"A1QA","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"904 - A1QA10 - Скидка 10% - От 70.00 рублей - Минск","code":"A1QA10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"905 - SKYWIND - Скидка 10% - От 16.99 рублей - Минск","code":"SKYWIND","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"906 - SKYWIND10 - Скидка 10% - От 70.00 рублей - Минск","code":"SKYWIND10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"996 - КАРПЕНКО - Скидка 7% - От 15.00 рублей - Минск","code":"КАРПЕНКО","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1111 - BARMASSE - Скидка 5% - От 15.00 рублей - Минск","code":"BARMASSE","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1118 - NIGHT, NIGHT1, NIGHT2 - Сырные палочки - От 15.00 рублей - Минск","code":"NIGHT","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1154 - ITECHART10 - Скидка 10% - От 70.00 рублей - Минск","code":"ITECHART10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1155 - ITECHART - Скидка 10% - От 16.99 рублей - Минск, Могилев, Витебск","code":"ITECHART","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1218 - WARGAMING - Скидка 10% - От 16.99 рублей - Минск","code":"WARGAMING","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1219 - WARGAMING10 - Скидка 10% - От 70.00 рублей - Минск","code":"WARGAMING10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1340 - LEVERX10 - Скидка 10% - От 16.99 рублей - Минск","code":"LEVERX10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1369 - AWESOME - Супер Папа 23ТРАД - От 25.00 рублей - Минск","code":"AWESOME","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1372 - AWESOME5, AWESOME7 - На выбор из 5 пицц 30ТРАД, 30ТОНК - От 33.00 рублей - Минск","code":"AWESOME5","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1376 - WONDER1 - Сырные Палочки - От 15.00 рублей - Минск","code":"WONDER1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1377 - WONDER7 - Картофельные Дольки - От 15.00 рублей - Минск","code":"WONDER7","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1378 - WONDER35, WONDER28 - На выбор из 5 пицц 23ТРАД - От 33.00 рублей - Минск","code":"WONDER35","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1419 - JUNO10 - Скидка 10% - От 16.99 рублей - Минск","code":"JUNO10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1443 - CACTUSSOFT10 - Скидка 10% - От 16.99 рублей - Минск","code":"CACTUSSOFT10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1507 - VELCOM10 - Скидка 10% - От 16.99 рублей - Минск","code":"VELCOM10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1513 - TPS10 - Скидка 10% - От 16.99 рублей - Минск","code":"TPS10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1524 - IDFINANCE10 - Скидка 10% - От 16.99 рублей - Минск","code":"IDFINANCE10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1610 - BLITZTEAM10 - Скидка 10% - От 16.99 рублей - Минск","code":"BLITZTEAM10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1693 - ВЕГЕТАРИАНСКАЯ - Вегетарианская 23ТРАД - От 15.00 рублей - Минск","code":"ВЕГЕТАРИАНСКАЯ","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1708 - LIGHTPOINT10 - Скидка 10% - От 16.99 рублей - Минск","code":"LIGHTPOINT10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1776 - HIQO10 - Скидка 10% - От 16.99 рублей - Минск","code":"HIQO10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1802 - TUROV10 - Скидка 10% - От 16.99 рублей - Минск","code":"TUROV10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1841 - QULIX - Скидка 10% - От 16.99 рублей - Минск","code":"QULIX","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1863 - NETCRACKER10 - Скидка 10% - От 16.99 рублей - Минск","code":"NETCRACKER10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1917 - ITCAFE10 - Скидка 10% - От 16.99 рублей - Минск","code":"ITCAFE10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1918 - ESOFT10 - Скидка 10% - От 16.99 рублей - Минск","code":"ESOFT10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1930 - СИНЕЗИС - Скидка 10% - От 16.99 рублей - Минск","code":"СИНЕЗИС","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1965 - Промокоды - На выбор из 5 пицц 30ТРАД, 30ТОНК - От 35.00 рублей - Минск, Гомель, Могилев, Витебск, Гродно","code":"PLAYTIKAPAPA1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1970 - LOVE23 - На выбор любая пицца 23ТРАД - От 27.00 рублей - Минск","code":"LOVE23","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1966 - Промокоды - На выбор из 5 пицц 35ТРАД, 35ТОНК - От 45.00 рублей - Минск, Гомель, Могилев, Витебск, Гродно","code":"PLAYTIKAPAPA2","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1967 - Промокоды - На выбор из 5 пицц 40ТРАД, 40ТОНК - От 55.00 рублей - Минск, Гомель, Могилев, Витебск, Гродно","code":"PLAYTIKAPAPA3","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1968 - Промокоды - На выбор из 5 пицц 23ТРАД, Большое шоколадное печенье, Пепперони роллы - От 25.00 рублей - Минск, Гомель, Могилев, Витебск, Гродно","code":"PLAYTIKAPAPA4","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"1973 - Промокоды - Скидка 10% - От 16.99 рублей - Минск, Гомель, Могилев, Витебск, Гродно","code":"MILA10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2040 - MOBILES10, NAVEKSOFT10, RAY10, ARSQUAD10, WMREPLY10, KLIKA10 - Скидка 10% - От 16.99 рублей - Минск","code":"MOBILES10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2041 - MOBILESPAPA1, NAVEKSOFTPAPA1, RAYPAPA1, ARSQUADPAPA1, WMREPLYPAPA1, KLIKAPAPA1 - На выбор из 5 пицц 30ТРАД, 30ТОНК - От 35.00 рублей - Минск","code":"MOBILESPAPA1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2042 - MOBILESPAPA2, NAVEKSOFTPAPA2, RAYPAPA2, ARSQUADPAPA2, WMREPLYPAPA2, KLIKAPAPA2 - На выбор из 5 пицц 35ТРАД, 35ТОНК - От 45.00 рублей - Минск","code":"MOBILESPAPA2","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2043 - MOBILESPAPA3, NAVEKSOFTPAPA3, RAYPAPA3, ARSQUADPAPA3, WMREPLYPAPA3, KLIKAPAPA3 - На выбор из 5 пицц 40ТРАД, 40ТОНК - От 55.00 рублей - Минск","code":"MOBILESPAPA3","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2044 - MOBILESPAPA4, NAVEKSOFTPAPA4, RAYPAPA4, ARSQUADPAPA4, WMREPLYPAPA4, KLIKAPAPA4 - На выбор из 5 пицц 23ТРАД, Большое шоколадное печенье, Пепперони роллы - От 25.00 рублей - Минск","code":"MOBILESPAPA4","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2103 - A1QAPAPA2 - На выбор из 5 пицц 35ТРАД, 35ТОНК - От 45.00 рублей - Могилев","code":"A1QAPAPA2","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2101 - A1QA - Скидка 10% - При заказе от 16.99 руб - Могилев","code":"A1QA","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2104 - A1QAPAPA3 - На выбор из 5 пицц 40ТРАД, 40ТОНК - От 55.00 рублей - Могилев","code":"A1QAPAPA3","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2105 - A1QAPAPA4 - На выбор из 5 пицц 23ТРАД, Большое шоколадное печенье, Пепперони роллы - От 25.00 рублей - Могилев","code":"A1QAPAPA4","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2102 - A1QAPAPA1 - На выбор из 5 пицц 30ТРАД, 30ТОНК - От 35.00 рублей - Могилев","code":"A1QAPAPA1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2115 - PAPACLUB110 - Скидка 10% - От 16.99 рублей - Минск","code":"PAPACLUB110","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2116 - CLUBPAPA11 - На выбор из 5 пицц 30ТРАД,30ТОНК - От 33.00 рублей - Минск","code":"CLUBPAPA11","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2117 - CLUBPAPA12 - На выбор из 5 пицц 35ТРАД,35ТОНК - От 43.00 рублей - Минск","code":"CLUBPAPA12","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2118 - CLUBPAPA13 - На выбор из 5 пицц 40ТРАД, 40ТОНК - От 53.00 рублей - Минск","code":"CLUBPAPA13","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2119 - CLUBPAPA14 - На выбор из 5 пицц 23ТРАД, Большое шоколадное печенье, Пепперони роллы - От 23.00 рублей - Гродно","code":"CLUBPAPA14","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2128 - ELATEPAPA1 - На выбор из 5 пицц 30ТРАД, 30ТОНК - От 35.00 рублей - Минск","code":"ELATEPAPA1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2127 - ELATESOFTWARE - Скидка 10% - При заказе от 16.99 руб - Минск","code":"ELATESOFTWARE","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2129 - ELATEPAPA2 - На выбор из 5 пицц 35ТРАД, 35ТОНК - От 45.00 рублей - Минск","code":"ELATEPAPA2","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2130 - ELATEPAPA3 - На выбор из 5 пицц 40ТРАД, 40ТОНК - От 55.00 рублей - Минск","code":"ELATEPAPA3","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2131 - ELATEPAPA4 - На выбор из 5 пицц 23ТРАД, Большое шоколадное печенье, Пепперони роллы - От 25.00 рублей - Минск","code":"ELATEPAPA4","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2115 - PAPACLUB210 - Скидка 10% - От 16.99 рублей - Могилев","code":"PAPACLUB210","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2115 - PAPACLUB310 - Скидка 10% - От 16.99 рублей - Гродно","code":"PAPACLUB310","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2116 - CLUBPAPA21 - На выбор из 5 пицц 30ТРАД,30ТОНК - От 33.00 рублей - Могилев","code":"CLUBPAPA21","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2116 - CLUBPAPA31 - На выбор из 5 пицц 30ТРАД, 30ТОНК - От 33.00 рублей - Гродно","code":"CLUBPAPA31","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2117 - CLUBPAPA22 - На выбор из 5 пицц 35ТРАД,35ТОНК - От 43.00 рублей - Могилев","code":"CLUBPAPA22","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2117 - CLUBPAPA32 - На выбор из 5 пицц 35ТРАД,35ТОНК - От 43.00 рублей - Гродно","code":"CLUBPAPA32","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2118 - CLUBPAPA23 - На выбор из 5 пицц 40ТРАД, 40ТОНК - От 53.00 рублей - Могилев","code":"CLUBPAPA23","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2118 - CLUBPAPA33 - На выбор из 5 пицц 40ТРАД, 40ТОНК - От 53.00 рублей - Гродно","code":"CLUBPAPA33","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2119 - CLUBPAPA24 - На выбор из 5 пицц 23ТРАД, Большое шоколадное печенье, Пепперони роллы - От 23.00 рублей - Могилев","code":"CLUBPAPA24","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2119 - CLUBPAPA34 - На выбор из 5 пицц 23ТРАД, Большое шоколадное печенье, Пепперони роллы - От 23.00 рублей - Гродно","code":"CLUBPAPA34","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2196 - MUSTARD1 - Горчичная 23ТРАД - От 22.00 рублей - Витебск, Могилев, Гродно, Гомель","code":"MUSTARD1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2198 - EPAMBELARUS - Скидка 10% - При заказе от 16.99 руб - Минск, Витебск, Гомель, Гродно, Могилев","code":"EPAMBELARUS","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2201 - EPAMPAPA3 - На выбор из 5 пицц 40ТРАД, 40ТОНК - От 55.00 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"EPAMPAPA3","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2200 - EPAMPAPA2 - На выбор из 5 пицц 35ТРАД, 35ТОНК - От 45.00 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"EPAMPAPA2","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2202 - EPAMPAPA4 - На выбор из 5 пицц 23ТРАД, Большое шоколадное печенье, Пепперони роллы - От 25.00 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"EPAMPAPA4","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2205 - VELCOMPAPA2 - На выбор из 5 пицц 35ТРАД, 35ТОНК - От 45.00 рублей - Гомель, Гродно, Могилев, Витебск","code":"VELCOMPAPA2","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2203 - VELCOMPAPA4 - На выбор из 5 пицц 23ТРАД, Большое шоколадное печенье, Пепперони роллы - От 25.00 рублей - Гомель, Гродно, Могилев, Витебск","code":"VELCOMPAPA4","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2206 - VELCOMPAPA1 - На выбор из 5 пицц 30ТРАД,30ТОНК - От 35.00 рублей - Гомель, Гродно, Могилев, Витебск","code":"VELCOMPAPA1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2204 - VELCOMPAPA3 - На выбор из 5 пицц 40ТРАД, 40ТОНК - От 55.00 рублей - Гомель, Гродно, Могилев, Витебск","code":"VELCOMPAPA3","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2210 - VELCOM10 - Скидка 10% - От 16.99 рублей - Гомель, Гродно, Могилев, Витебск","code":"VELCOM10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2211 - INSTALLERS10 - Скидка 10% - От 16.99 рублей - Минск, Гомель, Гродно, Могилев, Витебск","code":"INSTALLERS10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2215 - INSTALLERSPAPA4 - На выбор из 5 пицц 23ТРАД, Большое шоколадное печенье, Пепперони роллы - От 25.00 рублей - Минск, Гомель, Гродно, Могилев, Витебск","code":"INSTALLERSPAPA4","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2212 - INSTALLERSPAPA1 - На выбор из 5 пицц 30ТРАД, 30ТОНК - От 35.00 рублей - Минск, Гомель, Гродно, Могилев, Витебск","code":"INSTALLERSPAPA1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2213 - INSTALLERSPAPA2 - На выбор из 5 пицц 35ТРАД, 35ТОНК - От 45.00 рублей - Минск, Гомель, Гродно, Могилев, Витебск","code":"INSTALLERSPAPA2","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2214 - INSTALLERSPAPA3 - На выбор из 5 пицц 40ТРАД, 40ТОНК - От 55.00 рублей - Минск, Гомель, Гродно, Могилев, Витебск","code":"INSTALLERSPAPA3","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2297 - GISMARTPAPA3 - На выбор из 5 пицц 40ТРАД, 40ТОНК - От 55.00 рублей - Минск","code":"GISMARTPAPA3","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2294 - GISMART10 - Скидка 10% - При заказе от 16.99 руб - Минск","code":"GISMART10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2296 - GISMARTPAPA2 - На выбор из 5 пицц 35ТРАД, 35ТОНК - От 45.00 рублей - Минск","code":"GISMARTPAPA2","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2295 - GISMARTPAPA1 - На выбор из 5 пицц 30ТРАД, 30ТОНК - От 35.00 рублей - Минск","code":"GISMARTPAPA1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2298 - GISMARTPAPA4 - На выбор из 7 товаров* - От 25.00 рублей - Минск","code":"GISMARTPAPA4","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2326 - SEA2 - Морская 23ТРАД - От 25.00 рублей - Минск","code":"SEA2","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2327 - SEA - Морская 23ТРАД - От 22.00 рублей - Могилев, Гродно, Витебск, Гомель","code":"SEA","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2346 - ДА - Картофельные Дольки - От 15.00 рублей - Минск","code":"ДА","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2372 - ALFAPAPA10, ITRANSITION10 - Скидка 10% - От 16.99 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"ALFAPAPA10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2373 - ALFAPAPA1, ITRANSITION1 - На выбор из 5 пицц 30ТРАД, 30ТОНК - От 35.00 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"ALFAPAPA1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2374 - ALFAPAPA2, ITRANSITION2 - На выбор из 5 пицц 35ТРАД, 35ТОНК - От 45.00 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"ALFAPAPA2","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2375 - ALFAPAPA3, ITRANSITION3 - На выбор из 5 пицц 40ТРАД, 40ТОНК - От 55.00 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"ALFAPAPA3","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2376 - ALFAPAPA4, ITRANSITION4 - На выбор из 7 товаров* - От 25.00 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"ALFAPAPA4","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2403 - EXADELPAPA10 - Скидка 10% - От 16.99 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"EXADELPAPA10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2404 -  EXADELPAPA1 - На выбор из 5 пицц 30ТРАД, 30ТОНК - От 35.00 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"EXADELPAPA1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2405 - EXADELPAPA2 - На выбор из 5 пицц 35ТРАД, 35ТОНК - От 45.00 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"EXADELPAPA2","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2406 - EXADELPAPA3 - На выбор из 5 пицц 40ТРАД, 40ТОНК - От 55.00 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"EXADELPAPA3","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2407 - EXADELPAPA4 - На выбор из 7 товаров* - От 25.00 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"EXADELPAPA4","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2416 - NEW3 - На выбор из 2 пицц 23ТРАД - От 23.00 рублей - Могилев, Гродно, Витебск, Гомель","code":"NEW3","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2417 - BEST3 - Большая Бонанза 30ТРАД, 30ТОНК - От 40.00 рублей - Могилев, Гродно, Витебск, Гомель","code":"BEST3","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2420 - BEAPPY10 - Скидка 10% - От 16.99 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"BEAPPY10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2421 - BEAPPYPAPA1 - На выбор из 5 пицц 30ТРАД, 30ТОНК - От 35.00 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"BEAPPYPAPA1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2422 - BEAPPYPAPA2 - На выбор из 5 пицц 35ТРАД, 35ТОНК - От 45.00 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"BEAPPYPAPA2","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2423 - BEAPPYPAPA3 - На выбор из 5 пицц 40ТРАД, 40ТОНК - От 55.00 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"BEAPPYPAPA3","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2424 - BEAPPYPAPA4 - На выбор из 7 блюд* - От 25.00 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"BEAPPYPAPA4","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2453 -  PODAROK - На выбор из двух блюд - От 15.00 рублей - Минск, Гродно, Гомель, Могилев, Витебск","code":"PODAROK","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2463 - ТАКСИ - На выбор любая пицца 23ТРАД - От 29.00 рублей - Минск","code":"ТАКСИ","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2471 - NEW7 - На выбор из 2 пицц 23ТРАД - От 27.00 рублей - Минск","code":"NEW7","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2472 - SUPER9 - На выбор из 2 пицц 30ТРАД, 30ТОНК - От 47.00 рублей - Минск","code":"SUPER9","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2474 - ИСТОРИЯ - Пепперони 23ТРАД - От 15.00 рублей - Могилев, Гродно, Гомель, Витебск","code":"ИСТОРИЯ","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2473 - ПЕРЧИК, ПАРМЕЗАН - Пепперони 23ТРАД - От 15.00 рублей - Минск","code":"ПЕРЧИК","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2487 - SMM - Ветчина и грибы 23ТРАД - От 25.00 рублей - Минск, Могилев, Витебск, Гродно, Гомель","code":"SMM","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2496 - MAY - На выбор из 5 пицц 23ТРАД - От 23.00 рублей - Могилев, Витебск, Гродно, Гомель","code":"MAY","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2508 - GAMES - На выбор из 4 пицц 23ТРАД - От 23.00 рублей - Могилев, Гродно, Витебск, Гомель","code":"GAMES","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2507 - GAME - На выбор из 4 пицц 23ТРАД - От 25.00 рублей - Минск","code":"GAME","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2509 - AMASTY10, VITRUM10 - Скидка 10% - От 16.99 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"AMASTY10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2510 - AMASTYPAPA1, VITRUMPAPA1 - На выбор из 5 пицц 30ТРАД, 30ТОНК - От 35.00 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"AMASTYPAPA1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2511 - AMASTYPAPA2, VITRUMPAPA2 - На выбор из 5 пицц 35ТРАД, 35ТОНК - От 45.00 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"AMASTYPAPA2","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2512 - AMASTYPAPA3,VITRUMPAPA3 - На выбор из 5 пицц 40ТРАД, 40ТОНК - От 55.00 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"AMASTYPAPA3","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2513 - VITRUMPAPA4, AMASTYPAPA4 - На выбор из 7 блюд* - От 25.00 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"VITRUMPAPA4","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2519 - ПАПАДЖОНС - Сырные палочки - От 15.00 рублей - Гомель, Могилев, Витебск","code":"ПАПАДЖОНС","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2537 - ЖМИ - Ветчина и грибы 23ТРАД - От 22.00 рублей - Минск","code":"ЖМИ","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2540 - ЧЕРЕПАХА - На выбор из 5 пицц 23ТРАД - От 25.00 рублей - Минск, Могилев, Гродно, Витебск, Гомель","code":"ЧЕРЕПАХА","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2545 - CHEESE5 - На выбор из 5 пицц 30ТРАД, 30ТОНК - От 36.00 рублей - Минск","code":"CHEESE5","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2556 - GAMES10 - Скидка 10% - От 16.99 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"GAMES10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2559 -  GAMESPAPA3 - На выбор из 5 пицц 40ТРАД, 40ТОНК - От 55.00 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"GAMESPAPA3","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2560 - GAMESPAPA4 - На выбор из 7 блюд* - От 25.00 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"GAMESPAPA4","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2557 - GAMESPAPA1 - На выбор из 5 пицц 30ТРАД, 30ТОНК - От 35.00 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"GAMESPAPA1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2558 - GAMESPAPA2 - На выбор из 5 пицц 35ТРАД, 35ТОНК - От 45.00 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"GAMESPAPA2","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2564 - КАШАЛОТ - Пепперони роллы 12 шт - От 20.00 рублей - Минск, Витебск, Гомель, Гродно, Могилев","code":"КАШАЛОТ","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2580 - DOOR17 - На выбор из 3 пицц 23ТРАД - От 15.00 рублей - Витебск","code":"DOOR17","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2594 - JUNE - Пепперони роллы 12 шт - От 19.00 рублей - Могилев, Витебск, Гомель, Минск","code":"JUNE","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2595 - DOOR1, DOOR2, DOOR5, DOOR7 - На выбор из 3 пицц 23ТРАД - От 15.00 рублей - Минск","code":"DOOR1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2596 - BS10 - Скидка 10% - От 16.99 рублей - Минск","code":"BS10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2598 - BSPAPA2 - На выбор из 5 пицц 35ТРАД, 35ТОНК - От 45.00 рублей - Минск","code":"BSPAPA2","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2599 - BSPAPA3 - На выбор из 5 пицц 40ТРАД, 40ТОНК - От 55.00 рублей - Минск","code":"BSPAPA3","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2600 - BSPAPA4 - На выбор из 7 блюд* - От 25.00 рублей - Минск","code":"BSPAPA4","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2597 - BSPAPA1 - На выбор из 5 пицц 30ТРАД, 30ТОНК - От 35.00 рублей - Минск","code":"BSPAPA1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2620 - NEW4 - На выбор из 2 пицц 23ТРАД - От 23.00 рублей - Могилев, Гродно, Гомель, Витебск","code":"NEW4","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2621 - BEST4 - Супер Чизбургер 30ТРАД, 30ТОНК - От 40.00 рублей - Могилев, Гродно, Витебск, Гомель","code":"BEST4","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2628 - Промокоды - На выбор из 8 пицц 30ТОНК - От 26.00 рублей - Минск, Могилев, Гродно, Витебск, Гомель","code":"CAKE","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2638 - BANUBAPAPA1 - На выбор из 5 пицц 30ТРАД, 30ТОНК - От 35.00 рублей - Минск, Могилев, Гродно, Гомель, Витебск","code":"BANUBAPAPA1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2639 - BANUBAPAPA2 - На выбор из 5 пицц 35ТРАД, 35ТОНК - От 45.00 рублей - Минск, Могилев, Гродно, Гомель, Витебск","code":"BANUBAPAPA2","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2641 - BANUBAPAPA4 - На выбор из 7 блюд* - От 25.00 рублей - Минск, Могилев, Гродно, Гомель, Витебск","code":"BANUBAPAPA4","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2640 - BANUBAPAPA3 - На выбор из 5 пицц 40ТРАД, 40ТОНК - От 55.00 рублей - Минск, Могилев, Гродно, Гомель, Витебск","code":"BANUBAPAPA3","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2646 -  PAPA - На выбор из 3 пицц 23ТРАД - От 15.00 рублей - Минск, Гомель, Гродно, Витебск, Могилев","code":"РАРА","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2651 - TOMATO5 - На выбор из 5 пицц 30ТРАД, 30ТОНК - От 34.00 рублей - Минск","code":"TOMATO5","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2652 - PIZZA1 - На выбор из 5 пицц 23ТРАД - От 20.00 рублей - Могилев, Гродно, Витебск, Гомель","code":"PIZZA1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2637 - BANUBA10, SYNESIS10 - Скидка 10% - От 16.99 рублей - Минск, Могилев, Гродно, Гомель, Витебск","code":"BANUBA10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2674 - SILVERPAPA4, FORTEPAPA4, FUTUREPAPA4 - На выбор из 7 блюд* - От 25.00 рублей - Минск, Могилев, Гродно, Гомель, Витебск","code":"SILVERPAPA4","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2671 - SILVERPAPA1, FORTEPAPA1, FUTUREPAPA1 - На выбор из 5 пицц 30ТРАД, 30ТОНК - От 35.00 рублей - Минск, Могилев, Гродно, Гомель, Витебск","code":"SILVERPAPA1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2672 - SILVERPAPA2, FORTEPAPA2, FUTUREPAPA2 - На выбор из 5 пицц 35ТРАД, 35ТОНК - От 45.00 рублей - Минск, Могилев, Гродно, Гомель, Витебск","code":"SILVERPAPA2","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2670 - SILVER10, FORTE10, FUTURE10 - Скидка 10% - От 16.99 рублей - Минск, Могилев, Гродно, Гомель, Витебск","code":"SILVER10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2683 - NEW8 - На выбор из 2 пицц 23ТРАД - От 27.00 рублей - Минск","code":"NEW8","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2704 - ТИГР - Пепперони 23ТРАД - От 15.00 рублей - Минск, Могилев, Гомель, Гродно, Витебск","code":"ТИГР","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2719 - PAPAJOHNS - На выбор из 3 пицц 23ТРАД - От 18.00 рублей - Витебск, Гомель, Могилев","code":"PAPAJOHNS","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2735 - ЛЕТНИЙ - На выбор из 3 пицц 23ТРАД - От 22.00 рублей - Минск","code":"ЛЕТНИЙ","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2736 - РОЛИКИ - На выбор из 3 блюд - От 18.00 рублей - Минск","code":"РОЛИКИ","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2740 - ROLLS - На выбор из 3 блюд - От 19.00 рублей - Минск","code":"ROLLS","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2741 - ROLLS4 - На выбор из 3 блюд - От 19.00 рублей - Могилев, Гомель, Гродно, Витебск","code":"ROLLS4","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2743 - ПАПАПИЦЦА - На выбор любая пицца 23ТРАД - От 27.00 рублей - Минск, Гомель, Гродно, Витебск, Могилев","code":"ПАПАПИЦЦА","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2754 - ПАПАПИЦЦА1 - На выбор из 3 пицц 23ТРАД - От 23.00 рублей - Все города","code":"ПАПАПИЦЦА1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2755 - ПАПАПИЦЦА2 - На выбор из 3 пицц 23ТРАД - От 25.00 рублей - Все города","code":"ПАПАПИЦЦА2","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2770 - ПРИКЛЮЧЕНИЕ - На выбор из 5 пицц 23ТРАД - От 23.00 рублей - Все города","code":"ПРИКЛЮЧЕНИЕ","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2774 - OXAGILE10 - Скидка 10% - От 16.99 рублей - Все города","code":"OXAGILE10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2775 - OXAGILEPAPA1 - На выбор из 5 пицц 30ТРАД, 30ТОНК - От 35.00 рублей - Все города","code":"OXAGILEPAPA1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2776 - OXAGILEPAPA2 - На выбор из 5 пицц 35ТРАД, 35ТОНК - От 45.00 рублей - Все города","code":"OXAGILEPAPA2","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2777 - OXAGILEPAPA3 - На выбор из 5 пицц 40ТРАД, 40ТОНК - От 55.00 рублей - Все города","code":"OXAGILEPAPA3","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2778 - OXAGILEPAPA4 - На выбор из 7 блюд* - От 25.00 рублей - Все города","code":"OXAGILEPAPA4","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2808 - DOOR11 - На выбор из 3 пицц 23ТРАД - От 15.00 рублей - Минск","code":"DOOR11","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2809 - DOOR12, DOOR15 - На выбор из 3 пицц 23ТРАД - От 15.00 рублей - Гомель, Могилев","code":"DOOR12","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2820 - STREET - На выбор из 3 пицц 23ТРАД - От 15.00 рублей - Могилев, Гомель","code":"STREET","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2827 - DOOR14 - На выбор из 3 пицц 23ТРАД - От 15.00 рублей - Витебск","code":"DOOR14","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2834 -  BEST5 - Супер Папа 30ТРАД, 30ТОНК - От 40.00 рублей - Витебск, Гомель, Гродно, Могилев","code":"BEST5","image":"\/uploads\/image\/bf680e406ac47ea2a30b7f8fa41c6026.png","image_mobile_stock":"\/uploads\/image\/bf680e406ac47ea2a30b7f8fa41c6026.png","image_mobile_shop":"\/uploads\/image\/e836d01548d6c0606a7ddd37a0bcfcc1.png"},
  {"name":"2835 -  NEW5 - На выбор из 2 пицц 23ТРАД - От 23.00 рублей - Витебск, Гродно, Гомель, Могилев","code":"NEW5","image":"\/uploads\/image\/6b300a986927e4d1f57fac65d6345048.png","image_mobile_stock":"\/uploads\/image\/6b300a986927e4d1f57fac65d6345048.png","image_mobile_shop":"\/uploads\/image\/bb856ab8179839d2cbd32e82dd8bea64.png"},
  {"name":"2853 - ЖЕЛЕЗНЫЙ1 - На выбор из 5 пицц 30ТРАД,30ТОНК - От 32.00 рублей - Могилев, Гомель, Гродно, Витебск","code":"ЖЕЛЕЗНЫЙ1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2852 - ЖЕЛЕЗНЫЙ - На выбор из 5 пицц 30ТРАД, 30ТОНК - От 32.00 рублей - Минск","code":"ЖЕЛЕЗНЫЙ","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2860 - FRIDAY - На выбор из 5 пицц 23ТРАД - От 20.00 рублей - Минск","code":"FRIDAY","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2861 - FRIDAY1 - На выбор из 5 пицц 23ТРАД - От 20.00 рублей - Могилев, Гомель, Витебск, Гродно","code":"FRIDAY1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2862 -  FRIDAY2 - На выбор из 5 пицц 23ТРАД - От 20.00 рублей - Все города","code":"FRIDAY2","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2863 - FOOD - На выбор из 5 пицц 30ТРАД, 30ТОНК - От 30.00 рублей - Минск","code":"FOOD","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2864 - FOOD1 - На выбор из 5 пицц 30ТРАД, 30ТОНК - От 30.00 рублей - Могилев, Витебск, Гомель, Гродно","code":"FOOD1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2867 - MONDAY2 - На выбор из 3 блюд - От 18.00 рублей - Могилев, Гомель, Гродно, Витебск","code":"MONDAY2","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2866 - MONDAY1 - На выбор из 3 блюд - От 18.00 рублей - Минск","code":"MONDAY1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2868 - DREAM - На выбор из 5 пицц 23ТРАД - От 25.00 рублей - Минск","code":"DREAM","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2870 - MYDREAM - На выбор из 3 блюд - От 18.00 рублей - Все города","code":"MYDREAM","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2869 - DREAM - На выбор из 5 пицц 23ТРАД - От 25.00 рублей - Могилев. Гомель, Гродно, Витебск","code":"DREAM","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2872 -  ГОРОД - На выбор из 2 пицц 23ТРАД - От 15.00 рублей - Витебск, Могилев, Гомель","code":"ГОРОД","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2871 - ЛЕТО - Ветчина и грибы 23ТРАД - От 15.00 рублей - Все города","code":"ЛЕТО","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2877 - NEW9 - На выбор из 2 пицц 23ТРАД - От 28.00 рублей - Минск","code":"NEW9","image":"\/uploads\/image\/7b8c31d98dcd49550a36c35fb2d65068.png","image_mobile_stock":"\/uploads\/image\/7b8c31d98dcd49550a36c35fb2d65068.png","image_mobile_shop":"\/uploads\/image\/9e47cc67f3bd0fab94ed5ceb7649266f.png"},
  {"name":"2878 - SUPER2 - На выбор из 2 пицц 30ТРАД,30ТОНК - От 45.00 рублей - Минск","code":"SUPER2","image":"\/uploads\/image\/306fa16f14f4033db32a4c7b25fb1e45.png","image_mobile_stock":"\/uploads\/image\/306fa16f14f4033db32a4c7b25fb1e45.png","image_mobile_shop":"\/uploads\/image\/0cf50ad0da60d3acafcd9ea7ef403da0.png"},
  {"name":"2880 - ПЕСОК - На выбор из 2 пицц 23ТРАД - От 15.00 рублей - Все города","code":"ПЕСОК","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2888 - VETPAPA10 - Скидка 10% на всю сумму при онлайн-заказе - Все города","code":"VETPAPA10","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2889 - VETPAPA1 - На выбор из 5 пицц 30ТРАД,30ТОНК - От 35.00 рублей - Все города","code":"VETPAPA1","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2890 -  VETPAPA2 - На выбор из 5 пицц 35ТРАД, 35ТОНК - От 45.00 рублей - Все города","code":"VETPAPA2","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2891 - VETPAPA3 - На выбор из 5 пицц 40ТРАД,40ТОНК - От 55.00 рублей - Все города","code":"VETPAPA3","image":false,"image_mobile_stock":false,"image_mobile_shop":false},
  {"name":"2892 - VETPAPA4 - На выбор из 7 товаров* - От 25.00 рублей - Все города","code":"VETPAPA4","image":false,"image_mobile_stock":false,"image_mobile_shop":false}]}
